fixed AttributeError in store.py
```
ExaBGP version : 3.9.0
Python version : 2.7.7 (custom, *)  [GCC custom]
System Uname   : custom SMP custom
System MaxInt  : 9223372036854775807

peer 10.X.X.X ASN 64XXX

<type 'exceptions.AttributeError'>
'IPSelf' object has no attribute 'index'
Traceback (most recent call last):
  File "/exabgp/4.0.0/lib/exabgp/reactor/peer.py", line 613, in _run
    for action in self._main(direction):
  File "/exabgp/4.0.0/lib/exabgp/reactor/peer.py", line 563, in _main
    new_routes.next()
  File "/exabgp/4.0.0/lib/exabgp/reactor/protocol.py", line 304, in new_update
    for update in updates:
  File "/exabgp/4.0.0/lib/exabgp/rib/store.py", line 224, in updates
    if old_change.attributes.index() == change.attributes.index() and old_change.nlri.nexthop.index() == change.nlri.nexthop.index():
AttributeError: 'IPSelf' object has no attribute 'index'
```

While here fix annoying indentation.

Submitted by: verm666@